name: Deploy Astro SSR to Azure App Service

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Astro SSR app
        run: npm run build
        env:
          NODE_ENV: production
      
      - name: Verify build output
        run: |
          echo "Build completed. Checking output..."
          ls -la dist/
          ls -la dist/server/ || echo "No server directory"
          test -f dist/server/entry.mjs && echo "✅ entry.mjs exists" || echo "❌ entry.mjs missing"
      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'km-orchestrator'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './dist'
