name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create clean package.json
        run: |
          echo "Creating package.json from scratch..."
          cat > package.json << 'EOF'
          {
            "name": "km-orchestrator-ui",
            "type": "module",
            "version": "1.0.0",
            "scripts": {
              "dev": "astro dev",
              "start": "astro dev", 
              "build": "astro build",
              "preview": "astro preview",
              "astro": "astro"
            },
            "dependencies": {
              "astro": "^4.16.18"
            }
          }
          EOF
          
          echo "Verifying package.json:"
          cat package.json
          echo "Checking for BOM:"
          hexdump -C package.json | head -1
      
      - name: Create astro.config.mjs
        run: |
          echo "Creating astro.config.mjs..."
          cat > astro.config.mjs << 'EOF'
          import { defineConfig } from 'astro/config';

          export default defineConfig({
            output: 'static',
            build: {
              format: 'directory'
            },
            site: 'https://km-orchestrator.azurewebsites.net',
            base: '/diagnostics'
          });
          EOF
      
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json .astro dist
          npm install
      
      - name: Build site
        run: |
          npm run build
          echo "Build completed successfully!"
          ls -la dist/
      
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"
