name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Clean everything
        run: |
          rm -rf node_modules package-lock.json .astro dist
          echo "Cleaned all build artifacts"
      
      - name: Check for BOM in package.json
        run: |
          echo "Checking package.json for BOM:"
          hexdump -C package.json | head -2
          echo "First few characters:"
          head -c 10 package.json | od -c
      
      - name: Fix package.json if needed
        run: |
          # Remove BOM if present
          if [ "$(head -c 3 package.json | od -An -tx1)" = " ef bb bf" ]; then
            echo "BOM detected, removing..."
            tail -c +4 package.json > package.json.tmp && mv package.json.tmp package.json
          fi
          echo "Final package.json check:"
          head -c 10 package.json | od -c
      
      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install --no-package-lock
      
      - name: Build site
        run: |
          npm run build
          echo "Build completed successfully!"
          ls -la dist/
      
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"