name: Upload Only

on:
  push:
    branches: [ master ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create dist directory with our diagnostics page
        run: |
          # Create dist directory
          mkdir -p dist/diagnostics
          
          # Copy our diagnostics page
          if [ -f "src/pages/diagnostics/index.astro" ]; then
            # Convert the .astro file to HTML manually
            cp "src/pages/diagnostics/index.astro" "dist/diagnostics/index.html"
            
            # Remove the Astro frontmatter
            sed -i '/^---$/,/^---$/d' "dist/diagnostics/index.html"
          elif [ -f "km-orchestrator-ui/src/pages/diagnostics/index.astro" ]; then
            cp "km-orchestrator-ui/src/pages/diagnostics/index.astro" "dist/diagnostics/index.html"
            sed -i '/^---$/,/^---$/d' "dist/diagnostics/index.html"
          else
            echo "Could not find diagnostics file!"
            exit 1
          fi
          
          echo "Created dist with diagnostics:"
          ls -la dist/
          ls -la dist/diagnostics/
      
      - name: Upload to Azure (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          skip_app_build: true
          skip_api_build: true
