name: Deploy KM Orchestrator

on:
  push:
    branches: [ master, main ]
    paths: 
      - 'km-orchestrator/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd km-orchestrator
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'km-orchestrator'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_KM_ORCHESTRATOR }}
        package: './km-orchestrator'
