name: Deploy km-mcp-graphrag to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'km-mcp-graphrag/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd km-mcp-graphrag
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'km-mcp-graphrag'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_KM_GRAPHRAG }}
        package: ./km-mcp-graphrag