name: Deploy KM-MCP-SQL-DOCS to Azure

on:
  push:
    branches: [ main, master ]
    paths:
      - 'km-mcp-sql-docs/**'
      - '.github/workflows/deploy-km-docs.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: km-mcp-sql-docs
  WORKING_DIRECTORY: ./km-mcp-sql-docs
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create deployment package
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        zip -r ../deploy.zip . -x "*.git*" -x "*.venv*" -x "__pycache__/*" -x "*.pyc" -x "publish-profile.xml"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_KM_DOCS }}
        package: ./deploy.zip
    
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 45
        response=$(curl -s -o /dev/null -w "%{http_code}" https://km-mcp-sql-docs.azurewebsites.net/health)
        if [ $response -eq 200 ]; then
          echo "✅ Deployment successful - Health check passed"
        else
          echo "⚠️ Health check returned status: $response"
        fi
